# Root directory for Air
root = "."

# Temporary folder for build output
tmp_dir = "./tmp"

[build]
# Build only the main.go in cmd/api
cmd = "go build -buildvcs=false -o ./tmp/main ./cmd/api/main.go"
bin = "./tmp/main"
delay = 300
exclude_dir = ["tmp", "vendor", "deployment"]
include_ext = ["go"]
log = "build-errors.log"
stop_on_error = true

[watch]
include_dir = ["cmd", "internal", "pkg"]
include_ext = ["go"]
exclude_file = [".env"]

[log]
time = true
main_only = false

[misc]
clean_on_exit = true
