FROM golang:1.25.1

WORKDIR /app

# Install Air for hot reload
ENV GOBIN=/usr/local/bin
RUN go install github.com/air-verse/air@latest

# Copy Go modules first for caching
COPY go.mod ./
COPY go.sum ./
RUN go mod download

# Copy full source
COPY . .

# Run Air
CMD ["air"]
