services:
  db:
    image: postgres:15.8
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  app:
    build:
      context: ..
      dockerfile: deployment/docker/app/Dockerfile.prod
    container_name: starter-app
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
volumes:
  pg_data: