services:
  app:
    build:
      context: ..
      dockerfile: deployment/docker/app/Dockerfile.dev
    container_name: starter-app-dev
    ports:
      - "8080:8080"
    volumes:
      - ../:/app
    env_file:
      - ../.env
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      db:
        condition: service_healthy
    command: ["air"]
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8.12
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  pgadmin_data: