services:
  app:
    build:
      context: ..
      dockerfile: deployment/docker/app/Dockerfile.dev
    container_name: starter-app-dev
    ports:
      - "3000:3000"
    volumes:
      - ../:/app
    env_file:
      - ../.env
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      db:
        condition: service_healthy
    command: ["air"]

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      db:
        condition: service_healthy
