basePath: /
definitions:
  example_com_go-api_internal_delivery_user_requests.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  example_com_go-api_internal_delivery_user_requests.RegisterRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - name
    - password
    type: object
  example_com_go-api_internal_domain_userentity.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
    type: object
  internal_delivery_user.ErrorResponse:
    properties:
      error:
        example: Error message
        type: string
    type: object
  internal_delivery_user.TokenResponse:
    properties:
      token:
        example: jwt-token
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: afereydoon.s@gmail.com
    name: Fereydoon Salemi
  description: Clean Architecture API in Golang with JWT Authentication and Category/User
    Management.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Go Starter Kit API
  version: "1.0"
paths:
  /api/users/login:
    post:
      consumes:
      - application/json
      description: Authenticate a user and return a JWT token
      parameters:
      - description: Login Request
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/example_com_go-api_internal_delivery_user_requests.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_delivery_user.TokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_delivery_user.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/internal_delivery_user.ErrorResponse'
      summary: Login a user
      tags:
      - Users
  /api/users/register:
    post:
      consumes:
      - application/json
      description: Create a new user account
      parameters:
      - description: Register Request
        in: body
        name: registerRequest
        required: true
        schema:
          $ref: '#/definitions/example_com_go-api_internal_delivery_user_requests.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/example_com_go-api_internal_domain_userentity.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_delivery_user.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_delivery_user.ErrorResponse'
      summary: Register a new user
      tags:
      - Users
swagger: "2.0"
